lzc-sdk-version: "0.1"
name: Flare
package: cloud.lazycat.czyt.app.flare
version: 1.2.0
description: 一个现代的自托管文件共享平台
homepage: https://github.com/FlintSH/Flare
author: FlintSH
application:
  subdomain: flare
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://flare-app:3000/
services:
  flare-app:
    container_name: flare-app
    # upstream: flintsh/flare:2.0.0
    image: registry.lazycat.cloud/czyt/flintsh/flare:026a46610b48d1f8
    environment:
      - DATABASE_URL=postgresql://flare:{{ stable_secret "db_password" }}@flare-postgres:5432/flare?schema=public
      - NEXTAUTH_URL=https://${LAZYCAT_APP_DOMAIN}
      - NEXTAUTH_SECRET={{ stable_secret "nextauth_secret" }}
    depends_on:
      - flare-postgres
    binds:
      - /lzcapp/var/uploads:/app/uploads
  flare-postgres:
    container_name: flare-postgres
    # upstream: library/postgres:16.15-alpine
    image: registry.lazycat.cloud/czyt/library/postgres:aa0ae8e7056ea3ea
    environment:
      - POSTGRES_USER=flare
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
      - POSTGRES_DB=flare
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U flare
      start_period: 90s
