lzc-sdk-version: "0.1"
name: Flare
package: cloud.lazycat.czyt.app.flare
version: 1.2.0
description: 一个现代的自托管文件共享平台
homepage: https://github.com/FlintSH/Flare
author: FlintSH
application:
  subdomain: flare
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://flare-app:3000/
services:
  flare-app:
    container_name: flare-app
    image: registry.lazycat.cloud/czyt/flintsh/flare:1d7b01e583feb495
    environment:
      - DATABASE_URL=postgresql://flare:flarepassword@flare-postgres:5432/flare?schema=public
      - NEXTAUTH_URL=https://${LAZYCAT_APP_DOMAIN}
      - NEXTAUTH_SECRET=lazycat_flare
    depends_on:
      - flare-postgres
    binds:
      - /lzcapp/var/uploads:/app/uploads
  flare-postgres:
    container_name: flare-postgres
    image: registry.lazycat.cloud/czyt/library/postgres:b0193ab17e40d829
    environment:
      - POSTGRES_USER=flare
      - POSTGRES_PASSWORD=flarepassword
      - POSTGRES_DB=flare
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -U flare
      start_period: 90s